services:
  jenkins:
    build: .
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - JENKINS_ADMIN_ID=${JENKINS_ADMIN_ID}
      - JENKINS_ADMIN_PASSWORD=${JENKINS_ADMIN_PASSWORD}
      - CASC_JENKINS_CONFIG=/usr/share/jenkins/ref/casc.yaml
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - t2-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host:jenkins.dev.bit2big.com"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.frontend.loadbalancer.server.port=8080" 
    healthcheck:
        test: ["CMD-SHELL", "curl -f http://localhost:8080/login || exit 1"]
        interval: 30s
        timeout: 10s
        retries: 3
volumes:
  jenkins_home:

networks:
  t2-proxy:
    external: true